<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en">
<head>
<title>Partner | Kanwokanwo</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="format-detection" content="telephone=no">
<meta name="format-detection" content="email=no">
    <link rel="stylesheet" type="text/css" href="/style/public.css?20160427"/>
    <link rel="stylesheet" type="text/css" href="/style/frame.css?20160427"/>
    <link rel="stylesheet" type="text/css" href="/style/useragreement.css"/>
</head>
<body>
<%@include file="/WEB-INF/views/common/top.jsp" %>
<div class="index-main">
    <h2>Privacy Policy</h2>
    Date of Last Revision: April 27, 2016<br/>
At Kanwokanwo, our fundamental philosophy is “members first.” That value powers all of the decisions we make, including how we gather and respect your personal information.
We’ve crafted the policy below to be as clear and straightforward as possible. Our aim is for you—our members—to always feel informed and empowered with respect to your privacy on Kanwokanwo.
<h2>Introduction</h2>
Our registered users (“Members”) share their professional identities, engage with their network, exchange knowledge and professional insights, post and view relevant content, and find business and career opportunities. Content on some of our services is also visible to unregistered viewers (“Visitors”). We believe that our services allow our Members to effectively compete and achieve their full career potential. The cornerstone of our business is to focus on our Members first.
Maintaining your trust is our top priority, so we adhere to the following principles to protect your privacy:
•	We protect your personal information and will only provide it to third parties: (1) with your consent; (2) where it is necessary to carry out your instructions; (3) as reasonably necessary in order to provide our features and functionality to you; (4) when we reasonably believe it is required by law, subpoena or other legal process; or (5) as necessary to enforce our User Agreement or protect the rights, property, or safety of Kanwokanwo, our Members and Visitors, and the public.
•	We have implemented appropriate security safeguards designed to protect your information in accordance with industry standards.
This Privacy Policy applies to Kanwokanwo.com and the Kanwokanwo mobile application, Kanwokanwo platform technology (such as “Share on Kanwokanwo” plugins for publishers) and all other Kanwokanwo websites, apps, developer platforms and other products and services (collectively the “Services”). We may modify this Privacy Policy from time to time, and if we make material changes to it, we will provide notice through our Service, or by other means so that you may review the changes before you continue to use our Services. If you object to any changes, you may close your account. Continuing to use our Services after we publish or communicate a notice about any changes to this Privacy Policy means that you are consenting to the changes.
<h2>1. What information we collect</h2>
1.1. Data Controllers
If you have any concern about providing information to us or having such information displayed on our Services or otherwise used in any manner permitted in this Privacy Policy and the User Agreement, you should not become a Member, visit our websites, apps or otherwise use our Services. If you have already registered, you can close your accounts (e.g., Kanwokanwo).
We collect your personal information in the following ways:
1.2. Registration
To create an account on Kanwokanwo, you must provide us with at least your name, email address and/or mobile number, and a password and agree to our User Agreement and this Privacy Policy, which governs how we treat your information. You may provide additional information during the registration flow to help you build your profile and to provide you more customized services (for example: language-specific profile pages, updates, content, more relevant ads and career opportunities). You understand that, by creating an account, we and others will be able to identify you by your Kanwokanwo profile. We may also ask for your credit card details if you purchase certain additional services.
1.3. Profile Information
After you create an account, you may choose to provide additional information on your Kanwokanwo profile, such as descriptions of your skills, professional experience, and educational background. You can list honors, awards, professional affiliations, Group memberships, networking objectives, institutions or individuals that you follow, and other information including content. Subject to the settings you choose, your connections may provide recommendations and endorsements of you. Providing additional information enables you to derive more benefit from our Services by helping you express your professional identity; find other professionals, opportunities, and information; and help recruiters and business opportunities find you. It also enables us to serve you ads and other relevant content on and off of our Services.
1.4. Address Book and Other Services That Sync with Kanwokanwo
You may use our address book or “contacts” importer (or other similar features) to upload your address book into our Services. We store this information (including phone numbers) and use it to help you manage and leverage your contacts in connection with our Services. We also use this information to enhance your experience with our Services by helping you to grow your network by: identifying your contacts that are already Members of our Services; providing a template to send invitations on your behalf to your contacts that are not Members; and suggesting people you may know (even if not in your contacts) but are not yet connected with you on our Services. We may also use this information to show you and other Members that you share the same uploaded contacts who may or may not be Members.
Please note that when you send an invitation to connect to another individual on our Service (a “connection”) or to join our Service to connect with you, that person may have access to your email address or, for SMS invitations, mobile number because it may be displayed in the invitation. After sending these invitations, we may also remind your invitees of your invitation on your behalf. Your Kanwokanwo connections will also have access to your email address.
We make other tools available to sync information with our Services, and may also develop additional features that allow Members to use their account in conjunction with other third-party services. For example, our mobile applications allow you to sync your device’s calendar, email and/or contacts apps with our Services to show you the Kanwokanwo profiles of meeting attendees, email correspondents and/or your contacts.
Another example are software tools that allow you to see our and other public information about the people you email or meet with and leverage our Services to help you gain insights from and grow your network. If you grant these products (mobile applications or our other Services that sync external email and calendar services, such as “Kanwokanwo Connected”) permission to access your email and calendar accounts, they will access and may store some of your email header and calendar history information. Our products that sync with external email services may also temporarily cache message content for performance reasons, in a way that is unreadable by us and our service providers.
Any information that you upload or sync with our Services is covered by the User Agreement and this Privacy Policy. You can remove your information at your convenience using the features we make available or in accordance with Section 3. You can remove your address book and any other synced information at any time.
1.5. Customer Service
When you contact our customer support services (e.g. on our Help Center ), we may have to access your Messages, Groups and other contributions to our Services and collect the information we need to categorize your question, respond to it, and, if applicable, investigate any breach of our User Agreement or this Privacy Policy. We also use this information to track potential problems and trends and customize our support responses to better serve you. We do not use this information for advertising.
1.6. Using the Kanwokanwo Sites and Applications
We collect information when you use (whether as a Member or a Visitor) our websites, applications, our platform technology (such as “Share on Kanwokanwo” plugins for publishers) or other Services. For example, we collect information when you view or click on ads on and off our Services, perform a search, import your address book, join and participate in groups, participate in polls, install one of our mobile applications and apply to schools through our Services. If you are logged in on Kanwokanwo.com or another Service or one of our cookies on your device identifies you, your usage information and the log data described in Section 1.10 of this policy, such as your IP address, will be associated by us with your account. Even if you’re not logged into a Service, we log information about devices used to access our Services, including IP address.
1.7. Using Third-Party Services and Visiting Third-Party Sites
You allow us to receive information when you use your account to log in to a third-party website or application. Also, when you visit a third-party site that embeds our social plugins (such as “Share on Kanwokanwo” for publishers) we receive information that those pages have loaded in your web browser. If you are logged in as a Member when you visit sites with our plugins, we use this information to recommend tailored content to you. We will use this information to personalize the functionality we provide on third-party sites, including providing you insights from your professional network and allowing you to share information with your network. Our retention of this data is addressed in Section 3.2. We may provide reports containing aggregated impression information to institutions hosting our plugins and similar technologies to help them measure traffic to their websites, but no personal data.
You also allow us to receive information about your visits and interaction with the sites and services of our partners that include our cookies and similar technologies, unless you opt out. If you are not a Member, we rely on the online terms between you and our partners.
1.8. Cookies
We use cookies and similar technologies, including mobile application identifiers, to help us recognize you across different Services, learn about your interests both on and off our Services, improve your experience, increase security, measure use and effectiveness of our Services, and serve advertising. You can control cookies through your browser settings and other tools. By visiting our Services, you consent to the placement of cookies and beacons in your browser and HTML-based emails in accordance with this Privacy Policy.
1.9. Advertising Technologies and Web Beacons
We target (and measure the performance of) ads to Members, Visitors and others both on and off of our Services through a variety of ad networks and ad exchanges, using the following, whether separately or combined:
•	Advertising technologies on and off of our Services, like web beacons, pixels, ad tags, cookies, and mobile identifiers as permitted by mobile platforms;
•	Member-provided profile and contact information and categories;
•	Information inferred from a Member‘s profile;
•	Your use of our Services (for example, your search history , Groups participation, which pages you visit, your clicking on a Kanwokanwo ad, etc.) and log files generated as described in Section 1.10;
•	Information from 3rd parties (e.g. advertising partners, publishers and data aggregators) which we use in addition to the information from our cookies (and similar technologies), your profile and use of our Services.
We do not share your personal information with any third-party advertisers or ad networks for advertising without your separate permission. Note that, as described in Section 2.6, your profile is visible to other Members and through public search depending on your settings. Also, advertising partners may associate personal information collected by the advertiser directly from you with our cookies and similar technologies. In such instances, we contractually require such advertisers to obtain your explicit opt-in consent before doing so.
We may show you sponsored content in your network update stream (NUS), which will be designated as sponsored content and will behave like other NUS updates. If you take social action (for example, if you “like” or “comment” on the sponsored content), your action may be seen by your network and other Members who are shown the sponsored content after you have acted on it.
We adhere to self-regulatory principles for interest based advertising. If you wish to not receive targeted ads from most third party institutions, you may opt-out as described here. Please note this does not opt you out of being served advertising. You will continue to receive generic ads or targeted ads by institutions not listed with these opt-out tools. You can also opt out specifically from our use of cookies and similar technologies to track your behavior on third party sites. For non-Members, this opt out setting is here.
1.10. Log Files, IP Addresses, and Information About Your Computer and Mobile Device
When you visit or leave our Services (whether as a Member or Visitor) by clicking a hyperlink or when you view a third-party site that includes our plugin or cookies (or similar technology), we automatically receive the URL of the site from which you came or the one to which you are directed. Also, advertisers receive the URL of the page that you are on when you click an ad on or through our Services. We also receive the internet protocol (“IP”) address of your computer or the proxy server that you use to access the web, your computer operating system details, your type of web browser, your mobile device (including your mobile device identifier provided by your mobile device operating system), your mobile operating system (if you are accessing Kanwokanwo using a mobile device), and the name of your ISP or your mobile carrier. We may also receive location data passed to us from third-party services or GPS-enabled devices that you have set up, which we use to show you local information on our mobile applications and for fraud prevention and security purposes. Most mobile devices allow you to prevent real time location data being sent to us, and of course we will honor your settings.
In the case of our Android apps, you will be provided notice of the types of data (e.g. location) that will be sent to us. If you choose to use our app after this notice, we process this data to enable registration or preview product features for you. If you choose not to become a Member, we will delete this information.
1.11. Other
Our Services are a dynamic, innovative environment, which means we are always seeking to improve the Services we offer you. We often introduce new features, some of which may result in the collection of new information (for example, when the Endorsements feature launched, we began collecting information about skills for which Members were endorsed and the individuals who endorsed them). Furthermore, new partnerships or corporate acquisitions may result in new features, and we may potentially collect new types of information. If we start collecting substantially new types of personal information and materially change how we handle your data, we will modify this Privacy Policy and notify you in accordance with Section 4.3.

<h2>2. How we use your personal information</h2>
2.1. Consent to Kanwokanwo Processing Information About You
The personal information that you provide to us may reveal or allow others to identify aspects of your life that are not expressly stated on your profile (for example, your picture or your name may reveal your gender). By providing personal information to us when you create or update your account and profile, you are expressly and voluntarily accepting the terms and conditions of our User Agreement and freely accepting and agreeing to our processing of your personal information in ways set out by this Privacy Policy. Supplying to us any information deemed “sensitive” by applicable law is entirely voluntary on your part. You can withdraw or modify your consent to our collection and processing of the information you provide at any time, in accordance with the terms of this Privacy Policy and the User Agreement, by changing your account settings or your profile on Kanwokanwo , or by closing your Kanwokanwo accounts.
2.2. Kanwokanwo Communications
We communicate with you through email, notices posted on the Kanwokanwo websites or apps, messages to your Kanwokanwo inbox, and other means available through the Services, including mobile text messages and push notifications. Examples of these communications include: (1) welcome and engagement communications - informing you about how to best use our Services, new features, updates about other Members you are connected to and their actions, etc.; (2) service communications - these will cover service availability, security, and other issues about the functioning of our Services; (3) promotional communications - these include both email and Message messages (Message messages are only delivered to your Kanwokanwo InBox), and may contain promotional information directly or on behalf of our partners, including academic opportunities and information from institutions that are hiring. These messages will be sent to you based on your profile information and messaging preferences. We track the open rate of your Messages to provide your Message acceptance score. You may change your email and contact preferences at any time by signing into your account and changing your Kanwokanwo email settings. You can also opt out of promotional messages by sending a request to Kanwokanwo Help Center.
Please be aware that you cannot opt out of receiving service messages from us.
2.3. User Communications
Many communications that you initiate through our Services (for example, an invitation sent to a non-Member) will list your name and primary email address in the header of the message. Messages you initiate may also provide the recipient with aggregate information about your network (for example, how many people are in your network). Other communications that you initiate through the Services, like a request for an introduction, will list your name as the initiator but will not include your personal email address contact information. Once you have connected with an individual, regardless of who sent the invitation, your contact information will be shared with that individual.
We use automatic scanning technology to help protect you and other Members. Such technology checks links and other content in your Messages, network updates and Group contributions to help us identify and block malicious links and malware, reduce spam and optimize the delivery of our Services.
2.4. Service Development; Customized Experience
We use information and content that you and other Members provide to us to conduct researchand development for the improvement of our Services in order to provide you and other Members and Visitors with a better, more intuitive experience and drive membership growth and engagement on our Services and to help connect professionals to economic opportunity.
We also customize your experience and the experiences of others on our Services. For example, when you sign in to your account, we may display the names and photos of new Members who have recently joined your network or recent updates from your connections and institutions you follow. We try to show you content, such as news and presentations, that is relevant to you, your industry, or your profession. We also use Members information and content for invitations and communications promoting our Services that are tailored to the recipient.
2.5. Sharing Information with Affiliates
We may share your personal information with our affiliates (meaning entities controlled by, controlling or under common control with Kanwokanwo) outside of the Kanwokanwo entity that is your data controller as reasonably necessary to provide the Services. You are consenting to this sharing. We combine information internally across different Services.
2.6. Sharing Information with Third Parties
We offer a “public profile” feature that allows you as a Member to publish portions of your professional profile to the public Internet. This public profile will be indexed and displayed through public search engines when someone searches for your name. You may choose the parts of your profile that search engines index or completely opt out of this feature in your Kanwokanwo accountsettings. However, third-party search engines may not automatically update their caches, which may contain old public profile information. Unless you delete them, your profiles on Kanwokanwo.com and our corresponding app are always viewable on the respective Services.
The visibility of your professional profile to other Members depends on your degree of connection with the viewing Member, the subscriptions they may have, their usage of the Services, access channels and search types (e.g. by name or by keyword). For example, first degree connections can see your full profile and contact information. Others have more limited access, as detailed in our Help Center. Please note that recruiters and other such professional subscribers can see your full profile even if you did not approve their Message.
We do not rent or sell personal information that you have not posted on our Services, except as described in this Privacy Policy. We will not disclose personal information that is not published to your profile or generated through engagement with our other services or unless we have your separate consent, unless we have a good faith belief that disclosure is permitted by law or is reasonably necessary to: (1) comply with a legal requirement or process, including, but not limited to, civil and criminal subpoenas, court orders or other compulsory disclosures; (2) enforce this Privacy Policy or our User Agreement; (3) respond to claims of a violation of the rights of third parties; (4) respond to Member service inquiries; or (5) protect the rights, property, or safety of Kanwokanwo, our Services, our Members, Visitors, or the public. See Section 2.14 for additional details about our compliance with legal requests for information.
We support middleware providers that offer archiving solutions to firms subject to legal and regulatory archiving requirements, which, with your permission, facilitate the archiving of your communications and other activity by a third party for compliance purposes. Content distributed through our sharing features and third-party integrations may result in displaying some of your personal information outside of our Services. For example, when you post content to a Group that is open for public discussion, your content, including your name as the contributor, may be displayed in search engine results.
Also, if you have opted to bind any of your Service accounts to your Twitter, Facebook or other similar account, you can easily share content from our Services to these third party services, in accordance with your account settings (which you may change at any time) and respective policies of these third parties. Further, we allow third parties to look-up profile information (subject to your privacy settings) using your email address or first and last name information through its profile API (see Section 2.7. below).
Third parties (for example, your email provider) may give you the option to upload certain information in your contacts stored with us onto their own service. If you choose to share your contacts in this way, you will be granting your third party provider the right to store, access, disclose and use these contacts in the ways described in such third party's terms and privacy policy.
2.7. Third Parties Using Kanwokanwo Platform Services
We collaborate with and allow third parties to use our developer platform to offer services and functionality in conjunction with our Services. These third-party developers have either negotiated an agreement to use our platform technology or have agreed to our self-service API and Plugin terms in order to build applications (“Platform Applications”). Both the negotiated agreements and our API and Plugin terms contain restrictions on how third parties may access, store, and use the personal information you provide to us.
If you choose to use a Platform Application, you will be asked to confirm acceptance of the privacy policy and user agreement of the third-party developer. To revoke permission granted to a Platform Application, please visit your settings. Note, however, that even if you revoke the permission granted to a Platform Application, your connections may still be using the Platform Application, so the Platform Application may still have access to certain information about you, just as your connections do. You may opt out of providing information to third-party developers through your connections by accessing the “Turn on/off data sharing with third-party applications” control in the “Groups, Institutions, and Applications” tab under settings.
2.8. Polls and Surveys
Polls and Surveys may be conducted by us, Members, or third parties. Some third parties may target advertisements to you on the results page based on your answers in the poll. We or third parties may follow up with you via Message regarding your participation unless you have opted out of receiving Message messages. We may use third parties to deliver incentives to you to participate in surveys or polls. If the delivery of incentives requires your contact information, you may be asked to provide personal information to the third party fulfilling the incentive offer, which will be used only for the purpose of delivering incentives and verifying your contact information. It is up to you whether you provide this information, or whether you desire to take advantage of an incentive. Your consent to use any personal information for the purposes set forth in the poll or survey will be explicitly requested by the party conducting it. We are a member of the Council of American Survey Research Organizations (“CASRO”) and abides by CASRO guidelines for market research. You may opt out of participating in surveys by changing your settings to stop receiving these inquiries and requests.
2.9. Search
You can search for Members, academic opportunities, information about institutions. For example, you can find Members with particular experience, or Members that you may know from your school. You can also find academic opportunities and information about institutions.
2.10. Groups
If you participate in Groups, share content on your network update stream, or import a blog or other content, you should be aware that any information you choose to disclose using these services can be read, collected, and used by other Members in these forums, developers, and other third parties, including advertisers. We are not responsible for the information you choose to submit in these forums. Your Groups contributions are typically searchable on our Services and some content in Groups may be public and searchable on the Internet if the group owner has not closed the group for public discussions. You can identify closed groups by the padlock icon next to the group name. You can remove your Groups posts at any time. However, others may have copied and used the information that you shared.
2.11. Testimonials and Advertisements Placed through Kanwokanwo Ads
If you provide any testimonials about our goods or services or place advertisements through the Kanwokanwo Ads, we may post those testimonials and examples of advertisements you place in connection with our promotion of these services to third parties. Testimonials and advertisements may include your name and other personal information that you have provided. For more information about Kanwokanwo Ads, please see the Kanwokanwo Ads Terms of Use.
2.12. Talent Recruiting, Marketing and Sales Solutions
We offer customized people-search functionality along with organizational and communications tools (including activity alerts) as part of our talent recruiting, marketing and sales solutions. These services allow subscribers - generally, enterprises and professional organizations - to export limited information from Members’ public profiles, such as name, headline, current school, current level of education, and location (for example, Beijing Haidian), in order to effectively manage candidate sourcing. You may limit or prevent such subscribers from exporting your profile information by configuring your public profile visibility settings to restrict access to these fields. We do not provide email or other contact information to these subscribers. However, if you post that information as part of your profile it will be available to them and others. A recruiter or other such subscriber may also manage and store information it has independently obtained about you outside of our Services, such as a resume, in connection with our platform. Any personal information obtained independently of our Services will not be added by us to your profile and is not under our control but is subject to the policies of our recruiting, marketing or sales solution subscriber. We store such information on behalf of such subscriber who can remove it at any time. We do not further process such information.
2.13. Pages for Institutions, Schools, Influencers, and Other Entities
Certain pages on the Services are public (e.g., college pages), and any communications or information shared through them will be accessible by the entity that created them. If you follow a person or organization, you will be listed among its followers, which can be viewed by others including the page owner. We use aggregate information about followers and viewers to provide data about such pages’ performance (for example, visits and updates).
2.14. Compliance with Legal Process and Other Disclosures
It is possible that we may need to disclose personal information, profile information, or information about your activities as a Member or Visitor when required by law, subpoena, or other legal process, whether in China, or other jurisdictions, or if we have a good faith belief that disclosure is reasonably necessary to (1) investigate, prevent, or take action regarding suspected or actual illegal activities or to assist government enforcement agencies; (2) enforce the User Agreement, investigate and defend ourselves against any third-party claims or allegations, or protect the security or integrity of our Service; or (3) exercise or protect the rights, property, or safety of Kanwokanwo, our Members, personnel, or others. We attempt to notify Members about legal demands for their personal information when appropriate in our judgment, unless prohibited by law or court order or when the request is an emergency. In light of our principles, we may dispute such demands when we believe, in our discretion, that the requests are overbroad, vague or lack proper authority, but do not commit to challenge every demand. To find out more about how we engage with government requests for data see our Law Enforcement Data Request Guidelines.
2.15. Disclosures to Others as the Result of a Change in Control or Sale of Kanwokanwo Corporation
We may also disclose your personal information to a third party as part of a sale of the assets of Kanwokanwo Corporation, a subsidiary, or division, or as the result of a change in control of the institution or one of its affiliates, or in preparation for any of these events. Any third party to which we transfers or sells our assets will have the right to continue to use the personal and other information that you provide to us in the manner set out in this Privacy Policy.
2.16. Service Providers
We may employ third party institutions and individuals to facilitate our Services (e.g. maintenance, analysis, audit, marketing and development). These third parties have limited access to your information only to perform these tasks on our behalf and are obligated to Kanwokanwo not to disclose or use it for other purposes.
2.17 Data Processing Outside Your Country
We may transfer your information and process it outside your country of residence, wherever Kanwokanwo, its affiliates and service providers operate.

<h2>3. Your Choices & Obligations</h2>
3.1. Rights to Access, Correct, or Delete Your Information, and Closing Your Account
You have a right to (1) access, modify, correct, or delete your personal information controlled by Kanwokanwo regarding your profile, (2) change or remove your content, and (3) close your account. You can request your personal information that is not viewable on your profile or readily accessible to you (for example, your IP access logs) through Kanwokanwo‘s Help Center. If you close your account(s), your information will generally be removed from the Service within 24 hours. We generally delete closed account information and will de-personalize any logs or other backup information through the deletion process within 30 days of account closure, except as noted below.
Please note: Information you have shared with others (for example, through Message, network updates, content sharing, or Groups) or that others have copied may also remain visible after you have closed your account or deleted the information from your own profile. Groups content associated with closed accounts will show an unknown user as the source. In addition, you may not be able to access, correct, or eliminate any information about you that other Members copied or exported out of our Services, because this information may not be in our control. Your public profile may be displayed in search engine results until the search engine refreshes its cache.
3.2. Data Retention
We retain the personal information you provide while your account is in existence or as needed to provide you services. We may retain your personal information even after you have closed your account if retention is reasonably necessary to comply with our legal obligations, meet regulatory requirements, resolve disputes between Members, prevent fraud and abuse, or enforce this Privacy Policy and our User Agreement. We may retain personal information, for a limited period of time, if requested by law enforcement. Our Customer Service may retain information for as long as is necessary to provide support-related reporting and trend analysis only, but we generally delete or de-personalize closed account data consistent with Section 3.1., except in the case of our plugin impression data (i.e., the information that you visited on sites carrying our social plugin, but which you did not click on), which we de-personalize within 7 days (although we do maintain 30 days worth of webserver logs for security, debugging, and site stability purposes only) by creating aggregate data sets that cannot be traced back to individuals.

<h2>4. Important Information</h2>
4.1. Minimum Age
As described in Section 2.1 of the User Agreement, persons must be of Minimum Age to use Kanwokanwo.
4.2 Changes to this Privacy Policy
We may change this Privacy Policy from time to time. If we make significant changes in the way we treat your personal information, or to the Privacy Policy, we will provide notice to you on the Services or by some other means, such as email. Please review the changes carefully. If you agree to the changes, simply continue to use our Services. If you object to any of the changes to our terms and you no longer wish to use our Services, you may close your account(s). Unless stated otherwise, our current Privacy Policy applies to all information that we have about you and your account. Using our Services after a notice of changes has been communicated to you or published on our Services shall constitute consent to the changed terms or practices.
4.3 Security
We have implemented security safeguards designed to protect the personal information that you provide in accordance with industry standards. Access to your data on our Services is password-protected, and data such as credit card information is protected by SSL encryption when it is exchanged between your web browser and the Services. We also offer secure https access to the Kanwokanwo.com website. To protect any data you store on our servers, we also regularly monitor our system for possible vulnerabilities and attacks, and we use a tier-one secured-access data center. However, since the Internet is not a 100% secure environment, we cannot ensure or warrant the security of any information that you transmit to us. There is no guarantee that information may not be accessed, disclosed, altered, or destroyed by breach of any of our physical, technical, or managerial safeguards. It is your responsibility to protect the security of your login information. Please note that emails, instant messaging, and similar means of communication with other Members are not encrypted, and we strongly advise you not to communicate any confidential information through these means. Please help keep your account safe by using a strong password.



</div>

<link rel="stylesheet" type="text/css" href="/style/bottom.css"/>
<footer class="clearfix">
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <span>
                Learn more about Kanwokanwo <br>
                <a href="https://kanwo.daikeapp.com/">Visit our FAQ page</a><br>
                 © 2016.Kanwokanwo<br>
                  <em>京ICP备14049391号-1</em>
            </span>
        </div>
        <div class="col-md-4">
            <span class="bottom_links">
                <a href="/privacy_policy">Privacy Policy</a>&nbsp;|&nbsp;<a href="/terms_of_use">Terms of Use</a>
            </span>
        </div>
    </div>
</footer>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-75362333-1', 'auto');
  ga('send', 'pageview');
</script>
</body>
</html>